# Copyright (c) 2018-2019 Bitwise IO, Inc.
# Licensed under Creative Commons Attribution 4.0 International License
# https://creativecommons.org/licenses/by/4.0/
version: "2.1"

services:
  grid-docs-jekyll:
    build:
      dockerfile: docker/jekyll.dockerfile
      context: .
    image: grid-docs-jekyll
    container_name: grid-docs-jekyll
    working_dir: /srv/jekyll/
    ports:
      - 4000:4000
    volumes:
      - $PWD:/srv/jekyll
    environment:
      - JEKYLL_ENV=${JEKYLL_ENV}
    entrypoint:  |
      bash -c "
        rm -rf  _site
        jekyll serve --config ./_config.yml
      "

  grid-docs-redoc-0-1:
    container_name: grid-docs-redoc-0-1
    image: grid-docs-redoc
    build:
      dockerfile: docker/grid-docs-redoc
      context: .
    ports:
      - 4001:4001
    volumes:
      - .:/project
    entrypoint: |
      bash -c "
        cd /project/docs/0.1/references/api
        redoc-cli serve openapi.yaml -w -p 4001
      "

  grid-docs-redoc-0-2:
    container_name: grid-docs-redoc-0-2
    image: grid-docs-redoc
    build:
      dockerfile: docker/grid-docs-redoc
      context: .
    ports:
      - 4002:4002
    volumes:
      - .:/project
    entrypoint: |
      bash -c "
        cd /project/docs/0.2/references/api
        redoc-cli serve openapi.yaml -w -p 4002
      "

  grid-docs-apache:
    container_name: grid-docs-apache
    image: grid-docs-apache
    build:
      dockerfile: docker/grid-docs-apache
      context: .
    ports:
      - 8080:80
    volumes:
      - .:/project
      - ./database/postgres:/usr/local/apache2/htdocs/database/postgres
      - ./database/sqlite:/usr/local/apache2/htdocs/database/sqlite

  grid-docs-schemaspy-postgres-0-1:
    container_name: grid-docs-schemaspy-postgres-0-1
    image: grid-docs-schemaspy-postgres-0-1
    build:
      context: .
      dockerfile: docker/schemaspy/0-1/postgres/Dockerfile
    environment:
      HOST: db
      PORT: 5432
      DATABASE: grid
      USER: grid
      PASSWORD: grid_example
    depends_on:
      - db
    volumes:
      - ./database/postgres:/output

  grid-docs-schemaspy-sqlite-0-1:
    container_name: grid-docs-schemaspy-sqlite-0-1
    image: grid-docs-schemaspy-sqlite-0-1
    build:
      context: .
      dockerfile: docker/schemaspy/0-1/sqlite/Dockerfile
    depends_on:
      - db
    volumes:
      - ./database/sqlite:/output

  grid-docs-schemaspy-postgres-0-2:
    container_name: grid-docs-schemaspy-postgres-0-2
    image: grid-docs-schemaspy-postgres-0-2
    build:
      context: .
      dockerfile: docker/schemaspy/0-2/postgres/Dockerfile
    environment:
      HOST: db
      PORT: 5432
      DATABASE: grid
      USER: grid
      PASSWORD: grid_example
    depends_on:
      - db
    volumes:
      - ./database/postgres:/output

  grid-docs-schemaspy-sqlite-0-2:
    container_name: grid-docs-schemaspy-sqlite-0-2
    image: grid-docs-schemaspy-sqlite-0-2
    build:
      context: .
      dockerfile: docker/schemaspy/0-2/sqlite/Dockerfile
    depends_on:
      - db
    volumes:
      - ./database/sqlite:/output

  db:
    image: postgres
    container_name: db
    hostname: db
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_USER: grid
      POSTGRES_PASSWORD: grid_example
      POSTGRES_DB: grid
